variable "eks-vpc-cidr" {}
variable "eks-vpc-name" {}
variable "eks-vpc-igw-name" {}
variable "rt-1-name" {}
variable "rt-2-name" {}
variable "eks-subnet-1-cidr" {}
variable "eks-subnet-1-az" {}
variable "eks-subnet-1-name" {}
variable "eks-subnet-2-cidr" {}
variable "eks-subnet-2-az" {}
variable "eks-subnet-2-name" {}
variable "eks-sg-name" {}
variable "iam-role-eks" {}
variable "iam-role-node" {}
variable "iam-policy-eks" {}
variable "iam-policy-node" {}
variable "cluster-name" {}
variable "eksnode-group-name" {}
variable "vpc-cni-version" {}
variable "kube-proxy-version" {}